
set nocompatible 
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/nerdtree
" Plugin 'vim-pandoc/vim-pandoc'
"Plugin 'vim-pandoc/vim-pandoc-syntax'
"Plugin 'python-mode/python-mode'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'rhysd/vim-clang-format'
"Plugin 'pboettch/vim-cmake-syntax'
filetype plugin indent on

syntax on

set textwidth=80		" Set defulat text width to 80 chars.
set colorcolumn=+1
set fo=lbr		" fo specifies default formatting options.
set linebreak
set number      " Show line numbers by default.
set ruler       " Show the cursor position by default.
set cursorline  " Show the cursor line by default.
set noswapfile  " I'm thinking about info security.

" Set tab width to 4 spaces.
set tabstop=4           
set shiftwidth=4        
set softtabstop=0 noexpandtab
set hidden      " Allow vim to manage multiple buffers effectively.
set spelllang=en
set background=dark

" Useful tab completion.
set wildmenu
set wildmode=list:longest

set visualbell

" Move along displayed lines instead of physical lines.
noremap <buffer> <silent> k gk
noremap <buffer> <silent> j gj
noremap <buffer> <silent> 0 g0
noremap <buffer> <silent> $ g$
noremap <buffer> <silent> <Down> gj
noremap <buffer> <silent> <Up> gk

" Make find useful.
set path+=**

" YouCompleteMe makes annoying prompts otherwise.
let g:ycm_confirm_extra_conf=0
