
set nocompatible 
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax on			" Enable syntax highlighting.
filetype on			" Enable filetype detection.

set textwidth=80		" Set defulat text width to 80 chars.
set fo=lbr		" fo specifies default formatting options.
	" t - auto-wrap text
	" c - auto-wrap comments
	" r - auto-insert the current comment leader
	" q - allow formatting of comments.
set linebreak
set number      " Show line numbers by default.
set ruler       " Show the cursor position by default.
set cursorline  " Show the cursor line by default.
set noswapfile  " I'm thinking about info security.

" Set tab width to 4 spaces.
set tabstop=4           
set shiftwidth=4        
set softtabstop=0 noexpandtab
set hidden      " Allow vim to manage multiple buffers effectively.
set spelllang=en
set background=dark

let colorcolumn=join(range(100,999),",")
highlight ColorColumn ctermbg=1 guibg=lightgrey

" Useful tab completion.
set wildmenu
set wildmode=list:longest

set visualbell  " I never have my sound turned on, anyway...

" Allow me to move along displayed lines instead of physical lines.
noremap <buffer> <silent> k gk
noremap <buffer> <silent> j gj
noremap <buffer> <silent> 0 g0
noremap <buffer> <silent> $ g$
noremap <buffer> <silent> <Down> gj
noremap <buffer> <silent> <Up> gk

" Switch between .h and .cpp files wiht F4.
noremap <F4> :find %:p:s,.h$,.X123X,:s,.cpp$,.h,:s,.X123X$,.cpp,<CR>

" Make find useful.
set path+=**
