
set nocompatible 
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=$HOME/.vim/bundle/nerdtree
set rtp+=$HOME/.vim/bundle/ale
set rtp+=$HOME/projects/vim-virtualenv
set rtp+=$HOME/projects/vim-pipenv

filetype plugin indent on

syntax on

set textwidth=80		" Set defulat text width to 80 chars.
set colorcolumn=+1
set fo=lbr		" fo specifies default formatting options.
set linebreak
set number      " Show line numbers by default.
set ruler       " Show the cursor position by default.
set cursorline  " Show the cursor line by default.
set noswapfile  " I'm thinking about info security.

" Set tab width to 4 spaces.
set tabstop=4           
set shiftwidth=4        
set softtabstop=0 noexpandtab
set hidden      " Allow vim to manage multiple buffers effectively.
set spelllang=en
set background=dark

" Useful tab completion.
set wildmenu
set wildmode=list:longest

set visualbell

" Move along displayed lines instead of physical lines.
noremap <buffer> <silent> k gk
noremap <buffer> <silent> j gj
noremap <buffer> <silent> 0 g0
noremap <buffer> <silent> $ g$
noremap <buffer> <silent> <Down> gj
noremap <buffer> <silent> <Up> gk

" Make it easy to get to the vimrc and re-source the config.
nnoremap <leader>r :source $MYVIMRC<cr>
nnoremap <leader>e :edit $MYVIMRC<cr>

" Make find useful.
set path+=**

" Use ALE's completion.
let g:ale_completion_enabled=1
